//------------------------------------------------------------------------------
//        This code was generated by fable-css-modules.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------

[<RequireQualifiedAccess>]
module internal CssModules

open Fable.Core

type App =

    /// <summary>
    /// Binding for <c>form-designer-container</c> class
    /// </summary>
    [<Emit("$0[\"form-designer-container\"]")>]
    abstract ``form-designer-container`` : string

    /// <summary>
    /// Binding for <c>form-designer-container__component-list</c> class
    /// </summary>
    [<Emit("$0[\"form-designer-container__component-list\"]")>]
    abstract ``form-designer-container__component-list`` : string

    /// <summary>
    /// Binding for <c>form-designer-container__designer</c> class
    /// </summary>
    [<Emit("$0[\"form-designer-container__designer\"]")>]
    abstract ``form-designer-container__designer`` : string

    /// <summary>
    /// Binding for <c>form-designer-container__property-editor</c> class
    /// </summary>
    [<Emit("$0[\"form-designer-container__property-editor\"]")>]
    abstract ``form-designer-container__property-editor`` : string

